name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1.0. Configurar QEMU y Docker Buildx para construir imágenes multi-arquitectura
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2        

     # 1.1. ESTO ES LO QUE TE FALTA: Configurar el constructor para multi-plataforma
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        

      # 2. Login a GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build y push de la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64            
          tags: |
            ghcr.io/${{ github.repository_owner }}/seweb:latest        
            ghcr.io/${{ github.repository_owner }}/seweb:${{ github.sha }}